// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oposzxydezhxnqrphogu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wb3N6eHlkZXpoeG5xcnBob2d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2MjM2MzksImV4cCI6MjA1MDE5OTYzOX0.BfKx5L-TYv13vifHPdmyQBhtg4_3MEQxhEHdP7tLPGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);